sudo: false

language: elixir

elixir:
  - 1.8
  - 1.7

otp_release:
  - 21.1

cache:
  directories:
    - .plts

before_script:
  - mkdir -p .plts
  - "[[ -f .plts/local.plt ]] || mix dialyzer --plt"

script:
  - mix credo --strict
  - mix dialyzer --halt-exit-status
  - mix test
